# Register User
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Shah Md",
  "lastName": "Mahi",
  "username": "shahmdmahi",
  "email": "shahmdmahi24@gmail.com",
  "phone": "01757290258",
  "password": "Iliket90@abc",
  "confirmPassword": "Iliket90@abc"
}


###
# Resend Verification Email
POST http://localhost:5000/api/v1/auth/resend-verification
Content-Type: application/json

{
  "email": "shahmdmahi24@gmail.com"
}


###
# Verify Email
POST http://localhost:5000/api/v1/auth/verify-email
Content-Type: application/json

{
  "token": "11beced13c7e3dae4adc120b14a6b3f429ad2e5fbbef666b62e2ab13e48394783ca888c58cea1f0acfcbbfbf0558de87cdd9034bf6517fe15cd76c9975c87f24",
  "code": "214370"
}


###
# Login User
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "shahmdmahi",
  "password": "Iliket90@abc"
}


###