/*
  Warnings:

  - The values [USER_2FA_CODES_GENERATED,USER_2FA_RECOVERED] on the enum `AuditAction` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('USER_REGISTERED', 'USER_LOGGED_IN', 'USER_LOGGED_OUT', 'USER_FORGOT_PASSWORD', 'USER_RESET_PASSWORD', 'USER_RESEND_VERIFICATION', 'USER_2FA_ENABLED', 'USER_2FA_DISABLED', 'USER_2FA_CHALLENGED', 'USER_2FA_VERIFIED', 'USER_2FA_FAILED', 'USER_FAILED_LOGIN', 'USER_CHANGED_PASSWORD', 'USER_UPDATED_PROFILE', 'USER_VERIFIED', 'USER_APPROVED', 'USER_SUSPENDED', 'USER_BANNED', 'USER_LOCKED', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'SESSION_CREATED', 'SESSION_EXPIRED', 'SESSION_REVOKED', 'BLOG_PROFILE_CREATED', 'BLOG_PROFILE_UPDATED', 'BLOG_PROFILE_DELETED', 'BLOG_POST_CREATED', 'BLOG_POST_UPDATED', 'BLOG_POST_DELETED', 'BLOG_POST_STATUS_CHANGED', 'BLOG_POST_VISIBILITY_CHANGED', 'BLOG_POST_COMMENT_CREATED', 'BLOG_POST_COMMENT_UPDATED', 'BLOG_POST_COMMENT_DELETED');
ALTER TABLE "AuditLog" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;
