/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const Role = {
  SYSTEM_OWNER: "SYSTEM_OWNER",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  SYSTEM_MODERATOR: "SYSTEM_MODERATOR",
  SYSTEM_USER: "SYSTEM_USER",
  NORMAL_USER: "NORMAL_USER",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const DeviceType = {
  DESKTOP: "DESKTOP",
  MOBILE: "MOBILE",
  TABLET: "TABLET",
  TV: "TV",
  WEARABLE: "WEARABLE",
  CONSOLE: "CONSOLE",
  UNKNOWN: "UNKNOWN",
} as const;

export type DeviceType = (typeof DeviceType)[keyof typeof DeviceType];

export const BlogProfileVisibility = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
} as const;

export type BlogProfileVisibility =
  (typeof BlogProfileVisibility)[keyof typeof BlogProfileVisibility];

export const BlogPostVisibility = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
  UNLISTED: "UNLISTED",
} as const;

export type BlogPostVisibility =
  (typeof BlogPostVisibility)[keyof typeof BlogPostVisibility];

export const BlogPostStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;

export type BlogPostStatus =
  (typeof BlogPostStatus)[keyof typeof BlogPostStatus];

export const AuditEntity = {
  USER: "USER",
  SESSION: "SESSION",
  BLOG_PROFILE: "BLOG_PROFILE",
  BLOG_POST: "BLOG_POST",
  BLOG_POST_COMMENT: "BLOG_POST_COMMENT",
} as const;

export type AuditEntity = (typeof AuditEntity)[keyof typeof AuditEntity];

export const AuditAction = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  USER_FORGOT_PASSWORD: "USER_FORGOT_PASSWORD",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
  USER_RESEND_VERIFICATION: "USER_RESEND_VERIFICATION",
  USER_2FA_ENABLED: "USER_2FA_ENABLED",
  USER_2FA_DISABLED: "USER_2FA_DISABLED",
  USER_2FA_CHALLENGED: "USER_2FA_CHALLENGED",
  USER_2FA_VERIFIED: "USER_2FA_VERIFIED",
  USER_2FA_FAILED: "USER_2FA_FAILED",
  USER_FAILED_LOGIN: "USER_FAILED_LOGIN",
  USER_CHANGED_PASSWORD: "USER_CHANGED_PASSWORD",
  USER_UPDATED_PROFILE: "USER_UPDATED_PROFILE",
  USER_VERIFIED: "USER_VERIFIED",
  USER_APPROVED: "USER_APPROVED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_BANNED: "USER_BANNED",
  USER_LOCKED: "USER_LOCKED",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_REVOKED: "SESSION_REVOKED",
  BLOG_PROFILE_CREATED: "BLOG_PROFILE_CREATED",
  BLOG_PROFILE_UPDATED: "BLOG_PROFILE_UPDATED",
  BLOG_PROFILE_DELETED: "BLOG_PROFILE_DELETED",
  BLOG_POST_CREATED: "BLOG_POST_CREATED",
  BLOG_POST_UPDATED: "BLOG_POST_UPDATED",
  BLOG_POST_DELETED: "BLOG_POST_DELETED",
  BLOG_POST_STATUS_CHANGED: "BLOG_POST_STATUS_CHANGED",
  BLOG_POST_VISIBILITY_CHANGED: "BLOG_POST_VISIBILITY_CHANGED",
  BLOG_POST_COMMENT_CREATED: "BLOG_POST_COMMENT_CREATED",
  BLOG_POST_COMMENT_UPDATED: "BLOG_POST_COMMENT_UPDATED",
  BLOG_POST_COMMENT_DELETED: "BLOG_POST_COMMENT_DELETED",
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
