/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `BlogProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model BlogProfile
 *
 */
export type BlogProfileModel =
  runtime.Types.Result.DefaultSelection<Prisma.$BlogProfilePayload>;

export type AggregateBlogProfile = {
  _count: BlogProfileCountAggregateOutputType | null;
  _min: BlogProfileMinAggregateOutputType | null;
  _max: BlogProfileMaxAggregateOutputType | null;
};

export type BlogProfileMinAggregateOutputType = {
  id: string | null;
  userId: string | null;
  bio: string | null;
  website: string | null;
  location: string | null;
  visibility: $Enums.BlogProfileVisibility | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};

export type BlogProfileMaxAggregateOutputType = {
  id: string | null;
  userId: string | null;
  bio: string | null;
  website: string | null;
  location: string | null;
  visibility: $Enums.BlogProfileVisibility | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};

export type BlogProfileCountAggregateOutputType = {
  id: number;
  userId: number;
  bio: number;
  website: number;
  location: number;
  visibility: number;
  metadata: number;
  createdAt: number;
  updatedAt: number;
  deletedAt: number;
  _all: number;
};

export type BlogProfileMinAggregateInputType = {
  id?: true;
  userId?: true;
  bio?: true;
  website?: true;
  location?: true;
  visibility?: true;
  createdAt?: true;
  updatedAt?: true;
  deletedAt?: true;
};

export type BlogProfileMaxAggregateInputType = {
  id?: true;
  userId?: true;
  bio?: true;
  website?: true;
  location?: true;
  visibility?: true;
  createdAt?: true;
  updatedAt?: true;
  deletedAt?: true;
};

export type BlogProfileCountAggregateInputType = {
  id?: true;
  userId?: true;
  bio?: true;
  website?: true;
  location?: true;
  visibility?: true;
  metadata?: true;
  createdAt?: true;
  updatedAt?: true;
  deletedAt?: true;
  _all?: true;
};

export type BlogProfileAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which BlogProfile to aggregate.
   */
  where?: Prisma.BlogProfileWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of BlogProfiles to fetch.
   */
  orderBy?:
    | Prisma.BlogProfileOrderByWithRelationInput
    | Prisma.BlogProfileOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.BlogProfileWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` BlogProfiles from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` BlogProfiles.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned BlogProfiles
   **/
  _count?: true | BlogProfileCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: BlogProfileMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: BlogProfileMaxAggregateInputType;
};

export type GetBlogProfileAggregateType<T extends BlogProfileAggregateArgs> = {
  [P in keyof T & keyof AggregateBlogProfile]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBlogProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateBlogProfile[P]>;
};

export type BlogProfileGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.BlogProfileWhereInput;
  orderBy?:
    | Prisma.BlogProfileOrderByWithAggregationInput
    | Prisma.BlogProfileOrderByWithAggregationInput[];
  by: Prisma.BlogProfileScalarFieldEnum[] | Prisma.BlogProfileScalarFieldEnum;
  having?: Prisma.BlogProfileScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: BlogProfileCountAggregateInputType | true;
  _min?: BlogProfileMinAggregateInputType;
  _max?: BlogProfileMaxAggregateInputType;
};

export type BlogProfileGroupByOutputType = {
  id: string;
  userId: string;
  bio: string | null;
  website: string | null;
  location: string | null;
  visibility: $Enums.BlogProfileVisibility;
  metadata: runtime.JsonValue | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  _count: BlogProfileCountAggregateOutputType | null;
  _min: BlogProfileMinAggregateOutputType | null;
  _max: BlogProfileMaxAggregateOutputType | null;
};

type GetBlogProfileGroupByPayload<T extends BlogProfileGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<BlogProfileGroupByOutputType, T["by"]> & {
        [P in keyof T & keyof BlogProfileGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BlogProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BlogProfileGroupByOutputType[P]>;
      }
    >
  >;

export type BlogProfileWhereInput = {
  AND?: Prisma.BlogProfileWhereInput | Prisma.BlogProfileWhereInput[];
  OR?: Prisma.BlogProfileWhereInput[];
  NOT?: Prisma.BlogProfileWhereInput | Prisma.BlogProfileWhereInput[];
  id?: Prisma.StringFilter<"BlogProfile"> | string;
  userId?: Prisma.StringFilter<"BlogProfile"> | string;
  bio?: Prisma.StringNullableFilter<"BlogProfile"> | string | null;
  website?: Prisma.StringNullableFilter<"BlogProfile"> | string | null;
  location?: Prisma.StringNullableFilter<"BlogProfile"> | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFilter<"BlogProfile">
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.JsonNullableFilter<"BlogProfile">;
  createdAt?: Prisma.DateTimeFilter<"BlogProfile"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"BlogProfile"> | Date | string;
  deletedAt?:
    | Prisma.DateTimeNullableFilter<"BlogProfile">
    | Date
    | string
    | null;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  blogPosts?: Prisma.BlogPostListRelationFilter;
  blogPostComments?: Prisma.BlogPostCommentListRelationFilter;
};

export type BlogProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  bio?: Prisma.SortOrderInput | Prisma.SortOrder;
  website?: Prisma.SortOrderInput | Prisma.SortOrder;
  location?: Prisma.SortOrderInput | Prisma.SortOrder;
  visibility?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder;
  user?: Prisma.UserOrderByWithRelationInput;
  blogPosts?: Prisma.BlogPostOrderByRelationAggregateInput;
  blogPostComments?: Prisma.BlogPostCommentOrderByRelationAggregateInput;
};

export type BlogProfileWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    userId?: string;
    AND?: Prisma.BlogProfileWhereInput | Prisma.BlogProfileWhereInput[];
    OR?: Prisma.BlogProfileWhereInput[];
    NOT?: Prisma.BlogProfileWhereInput | Prisma.BlogProfileWhereInput[];
    bio?: Prisma.StringNullableFilter<"BlogProfile"> | string | null;
    website?: Prisma.StringNullableFilter<"BlogProfile"> | string | null;
    location?: Prisma.StringNullableFilter<"BlogProfile"> | string | null;
    visibility?:
      | Prisma.EnumBlogProfileVisibilityFilter<"BlogProfile">
      | $Enums.BlogProfileVisibility;
    metadata?: Prisma.JsonNullableFilter<"BlogProfile">;
    createdAt?: Prisma.DateTimeFilter<"BlogProfile"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"BlogProfile"> | Date | string;
    deletedAt?:
      | Prisma.DateTimeNullableFilter<"BlogProfile">
      | Date
      | string
      | null;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    blogPosts?: Prisma.BlogPostListRelationFilter;
    blogPostComments?: Prisma.BlogPostCommentListRelationFilter;
  },
  "id" | "userId"
>;

export type BlogProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  bio?: Prisma.SortOrderInput | Prisma.SortOrder;
  website?: Prisma.SortOrderInput | Prisma.SortOrder;
  location?: Prisma.SortOrderInput | Prisma.SortOrder;
  visibility?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder;
  _count?: Prisma.BlogProfileCountOrderByAggregateInput;
  _max?: Prisma.BlogProfileMaxOrderByAggregateInput;
  _min?: Prisma.BlogProfileMinOrderByAggregateInput;
};

export type BlogProfileScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.BlogProfileScalarWhereWithAggregatesInput
    | Prisma.BlogProfileScalarWhereWithAggregatesInput[];
  OR?: Prisma.BlogProfileScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.BlogProfileScalarWhereWithAggregatesInput
    | Prisma.BlogProfileScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"BlogProfile"> | string;
  userId?: Prisma.StringWithAggregatesFilter<"BlogProfile"> | string;
  bio?:
    | Prisma.StringNullableWithAggregatesFilter<"BlogProfile">
    | string
    | null;
  website?:
    | Prisma.StringNullableWithAggregatesFilter<"BlogProfile">
    | string
    | null;
  location?:
    | Prisma.StringNullableWithAggregatesFilter<"BlogProfile">
    | string
    | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityWithAggregatesFilter<"BlogProfile">
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"BlogProfile">;
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"BlogProfile">
    | Date
    | string;
  updatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<"BlogProfile">
    | Date
    | string;
  deletedAt?:
    | Prisma.DateTimeNullableWithAggregatesFilter<"BlogProfile">
    | Date
    | string
    | null;
};

export type BlogProfileCreateInput = {
  id?: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  user: Prisma.UserCreateNestedOneWithoutBlogProfileInput;
  blogPosts?: Prisma.BlogPostCreateNestedManyWithoutBlogProfileInput;
  blogPostComments?: Prisma.BlogPostCommentCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileUncheckedCreateInput = {
  id?: string;
  userId: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  blogPosts?: Prisma.BlogPostUncheckedCreateNestedManyWithoutBlogProfileInput;
  blogPostComments?: Prisma.BlogPostCommentUncheckedCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  user?: Prisma.UserUpdateOneRequiredWithoutBlogProfileNestedInput;
  blogPosts?: Prisma.BlogPostUpdateManyWithoutBlogProfileNestedInput;
  blogPostComments?: Prisma.BlogPostCommentUpdateManyWithoutBlogProfileNestedInput;
};

export type BlogProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  blogPosts?: Prisma.BlogPostUncheckedUpdateManyWithoutBlogProfileNestedInput;
  blogPostComments?: Prisma.BlogPostCommentUncheckedUpdateManyWithoutBlogProfileNestedInput;
};

export type BlogProfileCreateManyInput = {
  id?: string;
  userId: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
};

export type BlogProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
};

export type BlogProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
};

export type BlogProfileNullableScalarRelationFilter = {
  is?: Prisma.BlogProfileWhereInput | null;
  isNot?: Prisma.BlogProfileWhereInput | null;
};

export type BlogProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  bio?: Prisma.SortOrder;
  website?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  visibility?: Prisma.SortOrder;
  metadata?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  deletedAt?: Prisma.SortOrder;
};

export type BlogProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  bio?: Prisma.SortOrder;
  website?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  visibility?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  deletedAt?: Prisma.SortOrder;
};

export type BlogProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  bio?: Prisma.SortOrder;
  website?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  visibility?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  deletedAt?: Prisma.SortOrder;
};

export type BlogProfileScalarRelationFilter = {
  is?: Prisma.BlogProfileWhereInput;
  isNot?: Prisma.BlogProfileWhereInput;
};

export type BlogProfileCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutUserInput,
    Prisma.BlogProfileUncheckedCreateWithoutUserInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutUserInput;
  connect?: Prisma.BlogProfileWhereUniqueInput;
};

export type BlogProfileUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutUserInput,
    Prisma.BlogProfileUncheckedCreateWithoutUserInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutUserInput;
  connect?: Prisma.BlogProfileWhereUniqueInput;
};

export type BlogProfileUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutUserInput,
    Prisma.BlogProfileUncheckedCreateWithoutUserInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutUserInput;
  upsert?: Prisma.BlogProfileUpsertWithoutUserInput;
  disconnect?: Prisma.BlogProfileWhereInput | boolean;
  delete?: Prisma.BlogProfileWhereInput | boolean;
  connect?: Prisma.BlogProfileWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.BlogProfileUpdateToOneWithWhereWithoutUserInput,
      Prisma.BlogProfileUpdateWithoutUserInput
    >,
    Prisma.BlogProfileUncheckedUpdateWithoutUserInput
  >;
};

export type BlogProfileUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutUserInput,
    Prisma.BlogProfileUncheckedCreateWithoutUserInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutUserInput;
  upsert?: Prisma.BlogProfileUpsertWithoutUserInput;
  disconnect?: Prisma.BlogProfileWhereInput | boolean;
  delete?: Prisma.BlogProfileWhereInput | boolean;
  connect?: Prisma.BlogProfileWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.BlogProfileUpdateToOneWithWhereWithoutUserInput,
      Prisma.BlogProfileUpdateWithoutUserInput
    >,
    Prisma.BlogProfileUncheckedUpdateWithoutUserInput
  >;
};

export type EnumBlogProfileVisibilityFieldUpdateOperationsInput = {
  set?: $Enums.BlogProfileVisibility;
};

export type BlogProfileCreateNestedOneWithoutBlogPostsInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostsInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutBlogPostsInput;
  connect?: Prisma.BlogProfileWhereUniqueInput;
};

export type BlogProfileUpdateOneRequiredWithoutBlogPostsNestedInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostsInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutBlogPostsInput;
  upsert?: Prisma.BlogProfileUpsertWithoutBlogPostsInput;
  connect?: Prisma.BlogProfileWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.BlogProfileUpdateToOneWithWhereWithoutBlogPostsInput,
      Prisma.BlogProfileUpdateWithoutBlogPostsInput
    >,
    Prisma.BlogProfileUncheckedUpdateWithoutBlogPostsInput
  >;
};

export type BlogProfileCreateNestedOneWithoutBlogPostCommentsInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostCommentsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostCommentsInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutBlogPostCommentsInput;
  connect?: Prisma.BlogProfileWhereUniqueInput;
};

export type BlogProfileUpdateOneRequiredWithoutBlogPostCommentsNestedInput = {
  create?: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostCommentsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostCommentsInput
  >;
  connectOrCreate?: Prisma.BlogProfileCreateOrConnectWithoutBlogPostCommentsInput;
  upsert?: Prisma.BlogProfileUpsertWithoutBlogPostCommentsInput;
  connect?: Prisma.BlogProfileWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.BlogProfileUpdateToOneWithWhereWithoutBlogPostCommentsInput,
      Prisma.BlogProfileUpdateWithoutBlogPostCommentsInput
    >,
    Prisma.BlogProfileUncheckedUpdateWithoutBlogPostCommentsInput
  >;
};

export type BlogProfileCreateWithoutUserInput = {
  id?: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  blogPosts?: Prisma.BlogPostCreateNestedManyWithoutBlogProfileInput;
  blogPostComments?: Prisma.BlogPostCommentCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileUncheckedCreateWithoutUserInput = {
  id?: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  blogPosts?: Prisma.BlogPostUncheckedCreateNestedManyWithoutBlogProfileInput;
  blogPostComments?: Prisma.BlogPostCommentUncheckedCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileCreateOrConnectWithoutUserInput = {
  where: Prisma.BlogProfileWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutUserInput,
    Prisma.BlogProfileUncheckedCreateWithoutUserInput
  >;
};

export type BlogProfileUpsertWithoutUserInput = {
  update: Prisma.XOR<
    Prisma.BlogProfileUpdateWithoutUserInput,
    Prisma.BlogProfileUncheckedUpdateWithoutUserInput
  >;
  create: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutUserInput,
    Prisma.BlogProfileUncheckedCreateWithoutUserInput
  >;
  where?: Prisma.BlogProfileWhereInput;
};

export type BlogProfileUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.BlogProfileWhereInput;
  data: Prisma.XOR<
    Prisma.BlogProfileUpdateWithoutUserInput,
    Prisma.BlogProfileUncheckedUpdateWithoutUserInput
  >;
};

export type BlogProfileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  blogPosts?: Prisma.BlogPostUpdateManyWithoutBlogProfileNestedInput;
  blogPostComments?: Prisma.BlogPostCommentUpdateManyWithoutBlogProfileNestedInput;
};

export type BlogProfileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  blogPosts?: Prisma.BlogPostUncheckedUpdateManyWithoutBlogProfileNestedInput;
  blogPostComments?: Prisma.BlogPostCommentUncheckedUpdateManyWithoutBlogProfileNestedInput;
};

export type BlogProfileCreateWithoutBlogPostsInput = {
  id?: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  user: Prisma.UserCreateNestedOneWithoutBlogProfileInput;
  blogPostComments?: Prisma.BlogPostCommentCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileUncheckedCreateWithoutBlogPostsInput = {
  id?: string;
  userId: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  blogPostComments?: Prisma.BlogPostCommentUncheckedCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileCreateOrConnectWithoutBlogPostsInput = {
  where: Prisma.BlogProfileWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostsInput
  >;
};

export type BlogProfileUpsertWithoutBlogPostsInput = {
  update: Prisma.XOR<
    Prisma.BlogProfileUpdateWithoutBlogPostsInput,
    Prisma.BlogProfileUncheckedUpdateWithoutBlogPostsInput
  >;
  create: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostsInput
  >;
  where?: Prisma.BlogProfileWhereInput;
};

export type BlogProfileUpdateToOneWithWhereWithoutBlogPostsInput = {
  where?: Prisma.BlogProfileWhereInput;
  data: Prisma.XOR<
    Prisma.BlogProfileUpdateWithoutBlogPostsInput,
    Prisma.BlogProfileUncheckedUpdateWithoutBlogPostsInput
  >;
};

export type BlogProfileUpdateWithoutBlogPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  user?: Prisma.UserUpdateOneRequiredWithoutBlogProfileNestedInput;
  blogPostComments?: Prisma.BlogPostCommentUpdateManyWithoutBlogProfileNestedInput;
};

export type BlogProfileUncheckedUpdateWithoutBlogPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  blogPostComments?: Prisma.BlogPostCommentUncheckedUpdateManyWithoutBlogProfileNestedInput;
};

export type BlogProfileCreateWithoutBlogPostCommentsInput = {
  id?: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  user: Prisma.UserCreateNestedOneWithoutBlogProfileInput;
  blogPosts?: Prisma.BlogPostCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileUncheckedCreateWithoutBlogPostCommentsInput = {
  id?: string;
  userId: string;
  bio?: string | null;
  website?: string | null;
  location?: string | null;
  visibility?: $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string | null;
  blogPosts?: Prisma.BlogPostUncheckedCreateNestedManyWithoutBlogProfileInput;
};

export type BlogProfileCreateOrConnectWithoutBlogPostCommentsInput = {
  where: Prisma.BlogProfileWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostCommentsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostCommentsInput
  >;
};

export type BlogProfileUpsertWithoutBlogPostCommentsInput = {
  update: Prisma.XOR<
    Prisma.BlogProfileUpdateWithoutBlogPostCommentsInput,
    Prisma.BlogProfileUncheckedUpdateWithoutBlogPostCommentsInput
  >;
  create: Prisma.XOR<
    Prisma.BlogProfileCreateWithoutBlogPostCommentsInput,
    Prisma.BlogProfileUncheckedCreateWithoutBlogPostCommentsInput
  >;
  where?: Prisma.BlogProfileWhereInput;
};

export type BlogProfileUpdateToOneWithWhereWithoutBlogPostCommentsInput = {
  where?: Prisma.BlogProfileWhereInput;
  data: Prisma.XOR<
    Prisma.BlogProfileUpdateWithoutBlogPostCommentsInput,
    Prisma.BlogProfileUncheckedUpdateWithoutBlogPostCommentsInput
  >;
};

export type BlogProfileUpdateWithoutBlogPostCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  user?: Prisma.UserUpdateOneRequiredWithoutBlogProfileNestedInput;
  blogPosts?: Prisma.BlogPostUpdateManyWithoutBlogProfileNestedInput;
};

export type BlogProfileUncheckedUpdateWithoutBlogPostCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  visibility?:
    | Prisma.EnumBlogProfileVisibilityFieldUpdateOperationsInput
    | $Enums.BlogProfileVisibility;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  deletedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  blogPosts?: Prisma.BlogPostUncheckedUpdateManyWithoutBlogProfileNestedInput;
};

/**
 * Count Type BlogProfileCountOutputType
 */

export type BlogProfileCountOutputType = {
  blogPosts: number;
  blogPostComments: number;
};

export type BlogProfileCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  blogPosts?: boolean | BlogProfileCountOutputTypeCountBlogPostsArgs;
  blogPostComments?:
    | boolean
    | BlogProfileCountOutputTypeCountBlogPostCommentsArgs;
};

/**
 * BlogProfileCountOutputType without action
 */
export type BlogProfileCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfileCountOutputType
   */
  select?: Prisma.BlogProfileCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * BlogProfileCountOutputType without action
 */
export type BlogProfileCountOutputTypeCountBlogPostsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.BlogPostWhereInput;
};

/**
 * BlogProfileCountOutputType without action
 */
export type BlogProfileCountOutputTypeCountBlogPostCommentsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.BlogPostCommentWhereInput;
};

export type BlogProfileSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    userId?: boolean;
    bio?: boolean;
    website?: boolean;
    location?: boolean;
    visibility?: boolean;
    metadata?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    deletedAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    blogPosts?: boolean | Prisma.BlogProfile$blogPostsArgs<ExtArgs>;
    blogPostComments?:
      | boolean
      | Prisma.BlogProfile$blogPostCommentsArgs<ExtArgs>;
    _count?: boolean | Prisma.BlogProfileCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["blogProfile"]
>;

export type BlogProfileSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    userId?: boolean;
    bio?: boolean;
    website?: boolean;
    location?: boolean;
    visibility?: boolean;
    metadata?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    deletedAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["blogProfile"]
>;

export type BlogProfileSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    userId?: boolean;
    bio?: boolean;
    website?: boolean;
    location?: boolean;
    visibility?: boolean;
    metadata?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    deletedAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["blogProfile"]
>;

export type BlogProfileSelectScalar = {
  id?: boolean;
  userId?: boolean;
  bio?: boolean;
  website?: boolean;
  location?: boolean;
  visibility?: boolean;
  metadata?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
  deletedAt?: boolean;
};

export type BlogProfileOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "userId"
  | "bio"
  | "website"
  | "location"
  | "visibility"
  | "metadata"
  | "createdAt"
  | "updatedAt"
  | "deletedAt",
  ExtArgs["result"]["blogProfile"]
>;
export type BlogProfileInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  blogPosts?: boolean | Prisma.BlogProfile$blogPostsArgs<ExtArgs>;
  blogPostComments?: boolean | Prisma.BlogProfile$blogPostCommentsArgs<ExtArgs>;
  _count?: boolean | Prisma.BlogProfileCountOutputTypeDefaultArgs<ExtArgs>;
};
export type BlogProfileIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type BlogProfileIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $BlogProfilePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "BlogProfile";
  objects: {
    user: Prisma.$UserPayload<ExtArgs>;
    blogPosts: Prisma.$BlogPostPayload<ExtArgs>[];
    blogPostComments: Prisma.$BlogPostCommentPayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      userId: string;
      bio: string | null;
      website: string | null;
      location: string | null;
      visibility: $Enums.BlogProfileVisibility;
      metadata: runtime.JsonValue | null;
      createdAt: Date;
      updatedAt: Date;
      deletedAt: Date | null;
    },
    ExtArgs["result"]["blogProfile"]
  >;
  composites: {};
};

export type BlogProfileGetPayload<
  S extends boolean | null | undefined | BlogProfileDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$BlogProfilePayload, S>;

export type BlogProfileCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  BlogProfileFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: BlogProfileCountAggregateInputType | true;
};

export interface BlogProfileDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["BlogProfile"];
    meta: { name: "BlogProfile" };
  };
  /**
   * Find zero or one BlogProfile that matches the filter.
   * @param {BlogProfileFindUniqueArgs} args - Arguments to find a BlogProfile
   * @example
   * // Get one BlogProfile
   * const blogProfile = await prisma.blogProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BlogProfileFindUniqueArgs>(
    args: Prisma.SelectSubset<T, BlogProfileFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one BlogProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BlogProfileFindUniqueOrThrowArgs} args - Arguments to find a BlogProfile
   * @example
   * // Get one BlogProfile
   * const blogProfile = await prisma.blogProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BlogProfileFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, BlogProfileFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first BlogProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogProfileFindFirstArgs} args - Arguments to find a BlogProfile
   * @example
   * // Get one BlogProfile
   * const blogProfile = await prisma.blogProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BlogProfileFindFirstArgs>(
    args?: Prisma.SelectSubset<T, BlogProfileFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first BlogProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogProfileFindFirstOrThrowArgs} args - Arguments to find a BlogProfile
   * @example
   * // Get one BlogProfile
   * const blogProfile = await prisma.blogProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BlogProfileFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, BlogProfileFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more BlogProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BlogProfiles
   * const blogProfiles = await prisma.blogProfile.findMany()
   *
   * // Get first 10 BlogProfiles
   * const blogProfiles = await prisma.blogProfile.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const blogProfileWithIdOnly = await prisma.blogProfile.findMany({ select: { id: true } })
   *
   */
  findMany<T extends BlogProfileFindManyArgs>(
    args?: Prisma.SelectSubset<T, BlogProfileFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a BlogProfile.
   * @param {BlogProfileCreateArgs} args - Arguments to create a BlogProfile.
   * @example
   * // Create one BlogProfile
   * const BlogProfile = await prisma.blogProfile.create({
   *   data: {
   *     // ... data to create a BlogProfile
   *   }
   * })
   *
   */
  create<T extends BlogProfileCreateArgs>(
    args: Prisma.SelectSubset<T, BlogProfileCreateArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many BlogProfiles.
   * @param {BlogProfileCreateManyArgs} args - Arguments to create many BlogProfiles.
   * @example
   * // Create many BlogProfiles
   * const blogProfile = await prisma.blogProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends BlogProfileCreateManyArgs>(
    args?: Prisma.SelectSubset<T, BlogProfileCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many BlogProfiles and returns the data saved in the database.
   * @param {BlogProfileCreateManyAndReturnArgs} args - Arguments to create many BlogProfiles.
   * @example
   * // Create many BlogProfiles
   * const blogProfile = await prisma.blogProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many BlogProfiles and only return the `id`
   * const blogProfileWithIdOnly = await prisma.blogProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends BlogProfileCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, BlogProfileCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a BlogProfile.
   * @param {BlogProfileDeleteArgs} args - Arguments to delete one BlogProfile.
   * @example
   * // Delete one BlogProfile
   * const BlogProfile = await prisma.blogProfile.delete({
   *   where: {
   *     // ... filter to delete one BlogProfile
   *   }
   * })
   *
   */
  delete<T extends BlogProfileDeleteArgs>(
    args: Prisma.SelectSubset<T, BlogProfileDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one BlogProfile.
   * @param {BlogProfileUpdateArgs} args - Arguments to update one BlogProfile.
   * @example
   * // Update one BlogProfile
   * const blogProfile = await prisma.blogProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends BlogProfileUpdateArgs>(
    args: Prisma.SelectSubset<T, BlogProfileUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more BlogProfiles.
   * @param {BlogProfileDeleteManyArgs} args - Arguments to filter BlogProfiles to delete.
   * @example
   * // Delete a few BlogProfiles
   * const { count } = await prisma.blogProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends BlogProfileDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, BlogProfileDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more BlogProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BlogProfiles
   * const blogProfile = await prisma.blogProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends BlogProfileUpdateManyArgs>(
    args: Prisma.SelectSubset<T, BlogProfileUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more BlogProfiles and returns the data updated in the database.
   * @param {BlogProfileUpdateManyAndReturnArgs} args - Arguments to update many BlogProfiles.
   * @example
   * // Update many BlogProfiles
   * const blogProfile = await prisma.blogProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more BlogProfiles and only return the `id`
   * const blogProfileWithIdOnly = await prisma.blogProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends BlogProfileUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, BlogProfileUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one BlogProfile.
   * @param {BlogProfileUpsertArgs} args - Arguments to update or create a BlogProfile.
   * @example
   * // Update or create a BlogProfile
   * const blogProfile = await prisma.blogProfile.upsert({
   *   create: {
   *     // ... data to create a BlogProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BlogProfile we want to update
   *   }
   * })
   */
  upsert<T extends BlogProfileUpsertArgs>(
    args: Prisma.SelectSubset<T, BlogProfileUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__BlogProfileClient<
    runtime.Types.Result.GetResult<
      Prisma.$BlogProfilePayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of BlogProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogProfileCountArgs} args - Arguments to filter BlogProfiles to count.
   * @example
   * // Count the number of BlogProfiles
   * const count = await prisma.blogProfile.count({
   *   where: {
   *     // ... the filter for the BlogProfiles we want to count
   *   }
   * })
   **/
  count<T extends BlogProfileCountArgs>(
    args?: Prisma.Subset<T, BlogProfileCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], BlogProfileCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a BlogProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends BlogProfileAggregateArgs>(
    args: Prisma.Subset<T, BlogProfileAggregateArgs>
  ): Prisma.PrismaPromise<GetBlogProfileAggregateType<T>>;

  /**
   * Group by BlogProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends BlogProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BlogProfileGroupByArgs["orderBy"] }
      : { orderBy?: BlogProfileGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, BlogProfileGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetBlogProfileGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the BlogProfile model
   */
  readonly fields: BlogProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BlogProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BlogProfileClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  blogPosts<T extends Prisma.BlogProfile$blogPostsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.BlogProfile$blogPostsArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$BlogPostPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  blogPostComments<
    T extends Prisma.BlogProfile$blogPostCommentsArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<T, Prisma.BlogProfile$blogPostCommentsArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$BlogPostCommentPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the BlogProfile model
 */
export interface BlogProfileFieldRefs {
  readonly id: Prisma.FieldRef<"BlogProfile", "String">;
  readonly userId: Prisma.FieldRef<"BlogProfile", "String">;
  readonly bio: Prisma.FieldRef<"BlogProfile", "String">;
  readonly website: Prisma.FieldRef<"BlogProfile", "String">;
  readonly location: Prisma.FieldRef<"BlogProfile", "String">;
  readonly visibility: Prisma.FieldRef<"BlogProfile", "BlogProfileVisibility">;
  readonly metadata: Prisma.FieldRef<"BlogProfile", "Json">;
  readonly createdAt: Prisma.FieldRef<"BlogProfile", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"BlogProfile", "DateTime">;
  readonly deletedAt: Prisma.FieldRef<"BlogProfile", "DateTime">;
}

// Custom InputTypes
/**
 * BlogProfile findUnique
 */
export type BlogProfileFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * Filter, which BlogProfile to fetch.
   */
  where: Prisma.BlogProfileWhereUniqueInput;
};

/**
 * BlogProfile findUniqueOrThrow
 */
export type BlogProfileFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * Filter, which BlogProfile to fetch.
   */
  where: Prisma.BlogProfileWhereUniqueInput;
};

/**
 * BlogProfile findFirst
 */
export type BlogProfileFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * Filter, which BlogProfile to fetch.
   */
  where?: Prisma.BlogProfileWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of BlogProfiles to fetch.
   */
  orderBy?:
    | Prisma.BlogProfileOrderByWithRelationInput
    | Prisma.BlogProfileOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for BlogProfiles.
   */
  cursor?: Prisma.BlogProfileWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` BlogProfiles from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` BlogProfiles.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of BlogProfiles.
   */
  distinct?:
    | Prisma.BlogProfileScalarFieldEnum
    | Prisma.BlogProfileScalarFieldEnum[];
};

/**
 * BlogProfile findFirstOrThrow
 */
export type BlogProfileFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * Filter, which BlogProfile to fetch.
   */
  where?: Prisma.BlogProfileWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of BlogProfiles to fetch.
   */
  orderBy?:
    | Prisma.BlogProfileOrderByWithRelationInput
    | Prisma.BlogProfileOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for BlogProfiles.
   */
  cursor?: Prisma.BlogProfileWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` BlogProfiles from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` BlogProfiles.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of BlogProfiles.
   */
  distinct?:
    | Prisma.BlogProfileScalarFieldEnum
    | Prisma.BlogProfileScalarFieldEnum[];
};

/**
 * BlogProfile findMany
 */
export type BlogProfileFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * Filter, which BlogProfiles to fetch.
   */
  where?: Prisma.BlogProfileWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of BlogProfiles to fetch.
   */
  orderBy?:
    | Prisma.BlogProfileOrderByWithRelationInput
    | Prisma.BlogProfileOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing BlogProfiles.
   */
  cursor?: Prisma.BlogProfileWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` BlogProfiles from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` BlogProfiles.
   */
  skip?: number;
  distinct?:
    | Prisma.BlogProfileScalarFieldEnum
    | Prisma.BlogProfileScalarFieldEnum[];
};

/**
 * BlogProfile create
 */
export type BlogProfileCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * The data needed to create a BlogProfile.
   */
  data: Prisma.XOR<
    Prisma.BlogProfileCreateInput,
    Prisma.BlogProfileUncheckedCreateInput
  >;
};

/**
 * BlogProfile createMany
 */
export type BlogProfileCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many BlogProfiles.
   */
  data: Prisma.BlogProfileCreateManyInput | Prisma.BlogProfileCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * BlogProfile createManyAndReturn
 */
export type BlogProfileCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * The data used to create many BlogProfiles.
   */
  data: Prisma.BlogProfileCreateManyInput | Prisma.BlogProfileCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * BlogProfile update
 */
export type BlogProfileUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * The data needed to update a BlogProfile.
   */
  data: Prisma.XOR<
    Prisma.BlogProfileUpdateInput,
    Prisma.BlogProfileUncheckedUpdateInput
  >;
  /**
   * Choose, which BlogProfile to update.
   */
  where: Prisma.BlogProfileWhereUniqueInput;
};

/**
 * BlogProfile updateMany
 */
export type BlogProfileUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update BlogProfiles.
   */
  data: Prisma.XOR<
    Prisma.BlogProfileUpdateManyMutationInput,
    Prisma.BlogProfileUncheckedUpdateManyInput
  >;
  /**
   * Filter which BlogProfiles to update
   */
  where?: Prisma.BlogProfileWhereInput;
  /**
   * Limit how many BlogProfiles to update.
   */
  limit?: number;
};

/**
 * BlogProfile updateManyAndReturn
 */
export type BlogProfileUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * The data used to update BlogProfiles.
   */
  data: Prisma.XOR<
    Prisma.BlogProfileUpdateManyMutationInput,
    Prisma.BlogProfileUncheckedUpdateManyInput
  >;
  /**
   * Filter which BlogProfiles to update
   */
  where?: Prisma.BlogProfileWhereInput;
  /**
   * Limit how many BlogProfiles to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * BlogProfile upsert
 */
export type BlogProfileUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * The filter to search for the BlogProfile to update in case it exists.
   */
  where: Prisma.BlogProfileWhereUniqueInput;
  /**
   * In case the BlogProfile found by the `where` argument doesn't exist, create a new BlogProfile with this data.
   */
  create: Prisma.XOR<
    Prisma.BlogProfileCreateInput,
    Prisma.BlogProfileUncheckedCreateInput
  >;
  /**
   * In case the BlogProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.BlogProfileUpdateInput,
    Prisma.BlogProfileUncheckedUpdateInput
  >;
};

/**
 * BlogProfile delete
 */
export type BlogProfileDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
  /**
   * Filter which BlogProfile to delete.
   */
  where: Prisma.BlogProfileWhereUniqueInput;
};

/**
 * BlogProfile deleteMany
 */
export type BlogProfileDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which BlogProfiles to delete
   */
  where?: Prisma.BlogProfileWhereInput;
  /**
   * Limit how many BlogProfiles to delete.
   */
  limit?: number;
};

/**
 * BlogProfile.blogPosts
 */
export type BlogProfile$blogPostsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogPost
   */
  select?: Prisma.BlogPostSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogPost
   */
  omit?: Prisma.BlogPostOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostInclude<ExtArgs> | null;
  where?: Prisma.BlogPostWhereInput;
  orderBy?:
    | Prisma.BlogPostOrderByWithRelationInput
    | Prisma.BlogPostOrderByWithRelationInput[];
  cursor?: Prisma.BlogPostWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.BlogPostScalarFieldEnum | Prisma.BlogPostScalarFieldEnum[];
};

/**
 * BlogProfile.blogPostComments
 */
export type BlogProfile$blogPostCommentsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null;
  where?: Prisma.BlogPostCommentWhereInput;
  orderBy?:
    | Prisma.BlogPostCommentOrderByWithRelationInput
    | Prisma.BlogPostCommentOrderByWithRelationInput[];
  cursor?: Prisma.BlogPostCommentWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.BlogPostCommentScalarFieldEnum
    | Prisma.BlogPostCommentScalarFieldEnum[];
};

/**
 * BlogProfile without action
 */
export type BlogProfileDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the BlogProfile
   */
  select?: Prisma.BlogProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the BlogProfile
   */
  omit?: Prisma.BlogProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogProfileInclude<ExtArgs> | null;
};
