
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BlogPostComment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BlogPostComment
 * 
 */
export type BlogPostCommentModel = runtime.Types.Result.DefaultSelection<Prisma.$BlogPostCommentPayload>

export type AggregateBlogPostComment = {
  _count: BlogPostCommentCountAggregateOutputType | null
  _min: BlogPostCommentMinAggregateOutputType | null
  _max: BlogPostCommentMaxAggregateOutputType | null
}

export type BlogPostCommentMinAggregateOutputType = {
  id: string | null
  blogPostId: string | null
  blogProfileId: string | null
  content: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type BlogPostCommentMaxAggregateOutputType = {
  id: string | null
  blogPostId: string | null
  blogProfileId: string | null
  content: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type BlogPostCommentCountAggregateOutputType = {
  id: number
  blogPostId: number
  blogProfileId: number
  content: number
  metadata: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type BlogPostCommentMinAggregateInputType = {
  id?: true
  blogPostId?: true
  blogProfileId?: true
  content?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type BlogPostCommentMaxAggregateInputType = {
  id?: true
  blogPostId?: true
  blogProfileId?: true
  content?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type BlogPostCommentCountAggregateInputType = {
  id?: true
  blogPostId?: true
  blogProfileId?: true
  content?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type BlogPostCommentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BlogPostComment to aggregate.
   */
  where?: Prisma.BlogPostCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogPostComments to fetch.
   */
  orderBy?: Prisma.BlogPostCommentOrderByWithRelationInput | Prisma.BlogPostCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BlogPostCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogPostComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogPostComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BlogPostComments
  **/
  _count?: true | BlogPostCommentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BlogPostCommentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BlogPostCommentMaxAggregateInputType
}

export type GetBlogPostCommentAggregateType<T extends BlogPostCommentAggregateArgs> = {
      [P in keyof T & keyof AggregateBlogPostComment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBlogPostComment[P]>
    : Prisma.GetScalarType<T[P], AggregateBlogPostComment[P]>
}




export type BlogPostCommentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BlogPostCommentWhereInput
  orderBy?: Prisma.BlogPostCommentOrderByWithAggregationInput | Prisma.BlogPostCommentOrderByWithAggregationInput[]
  by: Prisma.BlogPostCommentScalarFieldEnum[] | Prisma.BlogPostCommentScalarFieldEnum
  having?: Prisma.BlogPostCommentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BlogPostCommentCountAggregateInputType | true
  _min?: BlogPostCommentMinAggregateInputType
  _max?: BlogPostCommentMaxAggregateInputType
}

export type BlogPostCommentGroupByOutputType = {
  id: string
  blogPostId: string
  blogProfileId: string
  content: string
  metadata: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: BlogPostCommentCountAggregateOutputType | null
  _min: BlogPostCommentMinAggregateOutputType | null
  _max: BlogPostCommentMaxAggregateOutputType | null
}

type GetBlogPostCommentGroupByPayload<T extends BlogPostCommentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BlogPostCommentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BlogPostCommentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BlogPostCommentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BlogPostCommentGroupByOutputType[P]>
      }
    >
  >



export type BlogPostCommentWhereInput = {
  AND?: Prisma.BlogPostCommentWhereInput | Prisma.BlogPostCommentWhereInput[]
  OR?: Prisma.BlogPostCommentWhereInput[]
  NOT?: Prisma.BlogPostCommentWhereInput | Prisma.BlogPostCommentWhereInput[]
  id?: Prisma.StringFilter<"BlogPostComment"> | string
  blogPostId?: Prisma.StringFilter<"BlogPostComment"> | string
  blogProfileId?: Prisma.StringFilter<"BlogPostComment"> | string
  content?: Prisma.StringFilter<"BlogPostComment"> | string
  metadata?: Prisma.JsonNullableFilter<"BlogPostComment">
  createdAt?: Prisma.DateTimeFilter<"BlogPostComment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BlogPostComment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"BlogPostComment"> | Date | string | null
  blogPost?: Prisma.XOR<Prisma.BlogPostScalarRelationFilter, Prisma.BlogPostWhereInput>
  blogProfile?: Prisma.XOR<Prisma.BlogProfileScalarRelationFilter, Prisma.BlogProfileWhereInput>
}

export type BlogPostCommentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  blogPostId?: Prisma.SortOrder
  blogProfileId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  blogPost?: Prisma.BlogPostOrderByWithRelationInput
  blogProfile?: Prisma.BlogProfileOrderByWithRelationInput
}

export type BlogPostCommentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BlogPostCommentWhereInput | Prisma.BlogPostCommentWhereInput[]
  OR?: Prisma.BlogPostCommentWhereInput[]
  NOT?: Prisma.BlogPostCommentWhereInput | Prisma.BlogPostCommentWhereInput[]
  blogPostId?: Prisma.StringFilter<"BlogPostComment"> | string
  blogProfileId?: Prisma.StringFilter<"BlogPostComment"> | string
  content?: Prisma.StringFilter<"BlogPostComment"> | string
  metadata?: Prisma.JsonNullableFilter<"BlogPostComment">
  createdAt?: Prisma.DateTimeFilter<"BlogPostComment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BlogPostComment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"BlogPostComment"> | Date | string | null
  blogPost?: Prisma.XOR<Prisma.BlogPostScalarRelationFilter, Prisma.BlogPostWhereInput>
  blogProfile?: Prisma.XOR<Prisma.BlogProfileScalarRelationFilter, Prisma.BlogProfileWhereInput>
}, "id">

export type BlogPostCommentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  blogPostId?: Prisma.SortOrder
  blogProfileId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BlogPostCommentCountOrderByAggregateInput
  _max?: Prisma.BlogPostCommentMaxOrderByAggregateInput
  _min?: Prisma.BlogPostCommentMinOrderByAggregateInput
}

export type BlogPostCommentScalarWhereWithAggregatesInput = {
  AND?: Prisma.BlogPostCommentScalarWhereWithAggregatesInput | Prisma.BlogPostCommentScalarWhereWithAggregatesInput[]
  OR?: Prisma.BlogPostCommentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BlogPostCommentScalarWhereWithAggregatesInput | Prisma.BlogPostCommentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BlogPostComment"> | string
  blogPostId?: Prisma.StringWithAggregatesFilter<"BlogPostComment"> | string
  blogProfileId?: Prisma.StringWithAggregatesFilter<"BlogPostComment"> | string
  content?: Prisma.StringWithAggregatesFilter<"BlogPostComment"> | string
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"BlogPostComment">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BlogPostComment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BlogPostComment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"BlogPostComment"> | Date | string | null
}

export type BlogPostCommentCreateInput = {
  id?: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  blogPost: Prisma.BlogPostCreateNestedOneWithoutCommentsInput
  blogProfile: Prisma.BlogProfileCreateNestedOneWithoutBlogPostCommentsInput
}

export type BlogPostCommentUncheckedCreateInput = {
  id?: string
  blogPostId: string
  blogProfileId: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BlogPostCommentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  blogPost?: Prisma.BlogPostUpdateOneRequiredWithoutCommentsNestedInput
  blogProfile?: Prisma.BlogProfileUpdateOneRequiredWithoutBlogPostCommentsNestedInput
}

export type BlogPostCommentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  blogPostId?: Prisma.StringFieldUpdateOperationsInput | string
  blogProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BlogPostCommentCreateManyInput = {
  id?: string
  blogPostId: string
  blogProfileId: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BlogPostCommentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BlogPostCommentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  blogPostId?: Prisma.StringFieldUpdateOperationsInput | string
  blogProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BlogPostCommentListRelationFilter = {
  every?: Prisma.BlogPostCommentWhereInput
  some?: Prisma.BlogPostCommentWhereInput
  none?: Prisma.BlogPostCommentWhereInput
}

export type BlogPostCommentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BlogPostCommentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  blogPostId?: Prisma.SortOrder
  blogProfileId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type BlogPostCommentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  blogPostId?: Prisma.SortOrder
  blogProfileId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type BlogPostCommentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  blogPostId?: Prisma.SortOrder
  blogProfileId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type BlogPostCommentCreateNestedManyWithoutBlogProfileInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput> | Prisma.BlogPostCommentCreateWithoutBlogProfileInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogProfileInputEnvelope
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
}

export type BlogPostCommentUncheckedCreateNestedManyWithoutBlogProfileInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput> | Prisma.BlogPostCommentCreateWithoutBlogProfileInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogProfileInputEnvelope
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
}

export type BlogPostCommentUpdateManyWithoutBlogProfileNestedInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput> | Prisma.BlogPostCommentCreateWithoutBlogProfileInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput[]
  upsert?: Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogProfileInput | Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogProfileInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogProfileInputEnvelope
  set?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  disconnect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  delete?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  update?: Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogProfileInput | Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogProfileInput[]
  updateMany?: Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogProfileInput | Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogProfileInput[]
  deleteMany?: Prisma.BlogPostCommentScalarWhereInput | Prisma.BlogPostCommentScalarWhereInput[]
}

export type BlogPostCommentUncheckedUpdateManyWithoutBlogProfileNestedInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput> | Prisma.BlogPostCommentCreateWithoutBlogProfileInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogProfileInput[]
  upsert?: Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogProfileInput | Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogProfileInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogProfileInputEnvelope
  set?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  disconnect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  delete?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  update?: Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogProfileInput | Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogProfileInput[]
  updateMany?: Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogProfileInput | Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogProfileInput[]
  deleteMany?: Prisma.BlogPostCommentScalarWhereInput | Prisma.BlogPostCommentScalarWhereInput[]
}

export type BlogPostCommentCreateNestedManyWithoutBlogPostInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput> | Prisma.BlogPostCommentCreateWithoutBlogPostInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogPostInputEnvelope
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
}

export type BlogPostCommentUncheckedCreateNestedManyWithoutBlogPostInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput> | Prisma.BlogPostCommentCreateWithoutBlogPostInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogPostInputEnvelope
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
}

export type BlogPostCommentUpdateManyWithoutBlogPostNestedInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput> | Prisma.BlogPostCommentCreateWithoutBlogPostInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput[]
  upsert?: Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogPostInput | Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogPostInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogPostInputEnvelope
  set?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  disconnect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  delete?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  update?: Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogPostInput | Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogPostInput[]
  updateMany?: Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogPostInput | Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogPostInput[]
  deleteMany?: Prisma.BlogPostCommentScalarWhereInput | Prisma.BlogPostCommentScalarWhereInput[]
}

export type BlogPostCommentUncheckedUpdateManyWithoutBlogPostNestedInput = {
  create?: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput> | Prisma.BlogPostCommentCreateWithoutBlogPostInput[] | Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput[]
  connectOrCreate?: Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput | Prisma.BlogPostCommentCreateOrConnectWithoutBlogPostInput[]
  upsert?: Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogPostInput | Prisma.BlogPostCommentUpsertWithWhereUniqueWithoutBlogPostInput[]
  createMany?: Prisma.BlogPostCommentCreateManyBlogPostInputEnvelope
  set?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  disconnect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  delete?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  connect?: Prisma.BlogPostCommentWhereUniqueInput | Prisma.BlogPostCommentWhereUniqueInput[]
  update?: Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogPostInput | Prisma.BlogPostCommentUpdateWithWhereUniqueWithoutBlogPostInput[]
  updateMany?: Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogPostInput | Prisma.BlogPostCommentUpdateManyWithWhereWithoutBlogPostInput[]
  deleteMany?: Prisma.BlogPostCommentScalarWhereInput | Prisma.BlogPostCommentScalarWhereInput[]
}

export type BlogPostCommentCreateWithoutBlogProfileInput = {
  id?: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  blogPost: Prisma.BlogPostCreateNestedOneWithoutCommentsInput
}

export type BlogPostCommentUncheckedCreateWithoutBlogProfileInput = {
  id?: string
  blogPostId: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BlogPostCommentCreateOrConnectWithoutBlogProfileInput = {
  where: Prisma.BlogPostCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput>
}

export type BlogPostCommentCreateManyBlogProfileInputEnvelope = {
  data: Prisma.BlogPostCommentCreateManyBlogProfileInput | Prisma.BlogPostCommentCreateManyBlogProfileInput[]
  skipDuplicates?: boolean
}

export type BlogPostCommentUpsertWithWhereUniqueWithoutBlogProfileInput = {
  where: Prisma.BlogPostCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.BlogPostCommentUpdateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedUpdateWithoutBlogProfileInput>
  create: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogProfileInput>
}

export type BlogPostCommentUpdateWithWhereUniqueWithoutBlogProfileInput = {
  where: Prisma.BlogPostCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.BlogPostCommentUpdateWithoutBlogProfileInput, Prisma.BlogPostCommentUncheckedUpdateWithoutBlogProfileInput>
}

export type BlogPostCommentUpdateManyWithWhereWithoutBlogProfileInput = {
  where: Prisma.BlogPostCommentScalarWhereInput
  data: Prisma.XOR<Prisma.BlogPostCommentUpdateManyMutationInput, Prisma.BlogPostCommentUncheckedUpdateManyWithoutBlogProfileInput>
}

export type BlogPostCommentScalarWhereInput = {
  AND?: Prisma.BlogPostCommentScalarWhereInput | Prisma.BlogPostCommentScalarWhereInput[]
  OR?: Prisma.BlogPostCommentScalarWhereInput[]
  NOT?: Prisma.BlogPostCommentScalarWhereInput | Prisma.BlogPostCommentScalarWhereInput[]
  id?: Prisma.StringFilter<"BlogPostComment"> | string
  blogPostId?: Prisma.StringFilter<"BlogPostComment"> | string
  blogProfileId?: Prisma.StringFilter<"BlogPostComment"> | string
  content?: Prisma.StringFilter<"BlogPostComment"> | string
  metadata?: Prisma.JsonNullableFilter<"BlogPostComment">
  createdAt?: Prisma.DateTimeFilter<"BlogPostComment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BlogPostComment"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"BlogPostComment"> | Date | string | null
}

export type BlogPostCommentCreateWithoutBlogPostInput = {
  id?: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  blogProfile: Prisma.BlogProfileCreateNestedOneWithoutBlogPostCommentsInput
}

export type BlogPostCommentUncheckedCreateWithoutBlogPostInput = {
  id?: string
  blogProfileId: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BlogPostCommentCreateOrConnectWithoutBlogPostInput = {
  where: Prisma.BlogPostCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput>
}

export type BlogPostCommentCreateManyBlogPostInputEnvelope = {
  data: Prisma.BlogPostCommentCreateManyBlogPostInput | Prisma.BlogPostCommentCreateManyBlogPostInput[]
  skipDuplicates?: boolean
}

export type BlogPostCommentUpsertWithWhereUniqueWithoutBlogPostInput = {
  where: Prisma.BlogPostCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.BlogPostCommentUpdateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedUpdateWithoutBlogPostInput>
  create: Prisma.XOR<Prisma.BlogPostCommentCreateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedCreateWithoutBlogPostInput>
}

export type BlogPostCommentUpdateWithWhereUniqueWithoutBlogPostInput = {
  where: Prisma.BlogPostCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.BlogPostCommentUpdateWithoutBlogPostInput, Prisma.BlogPostCommentUncheckedUpdateWithoutBlogPostInput>
}

export type BlogPostCommentUpdateManyWithWhereWithoutBlogPostInput = {
  where: Prisma.BlogPostCommentScalarWhereInput
  data: Prisma.XOR<Prisma.BlogPostCommentUpdateManyMutationInput, Prisma.BlogPostCommentUncheckedUpdateManyWithoutBlogPostInput>
}

export type BlogPostCommentCreateManyBlogProfileInput = {
  id?: string
  blogPostId: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BlogPostCommentUpdateWithoutBlogProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  blogPost?: Prisma.BlogPostUpdateOneRequiredWithoutCommentsNestedInput
}

export type BlogPostCommentUncheckedUpdateWithoutBlogProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  blogPostId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BlogPostCommentUncheckedUpdateManyWithoutBlogProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  blogPostId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BlogPostCommentCreateManyBlogPostInput = {
  id?: string
  blogProfileId: string
  content: string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BlogPostCommentUpdateWithoutBlogPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  blogProfile?: Prisma.BlogProfileUpdateOneRequiredWithoutBlogPostCommentsNestedInput
}

export type BlogPostCommentUncheckedUpdateWithoutBlogPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  blogProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BlogPostCommentUncheckedUpdateManyWithoutBlogPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  blogProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type BlogPostCommentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  blogPostId?: boolean
  blogProfileId?: boolean
  content?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  blogPost?: boolean | Prisma.BlogPostDefaultArgs<ExtArgs>
  blogProfile?: boolean | Prisma.BlogProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["blogPostComment"]>

export type BlogPostCommentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  blogPostId?: boolean
  blogProfileId?: boolean
  content?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  blogPost?: boolean | Prisma.BlogPostDefaultArgs<ExtArgs>
  blogProfile?: boolean | Prisma.BlogProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["blogPostComment"]>

export type BlogPostCommentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  blogPostId?: boolean
  blogProfileId?: boolean
  content?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  blogPost?: boolean | Prisma.BlogPostDefaultArgs<ExtArgs>
  blogProfile?: boolean | Prisma.BlogProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["blogPostComment"]>

export type BlogPostCommentSelectScalar = {
  id?: boolean
  blogPostId?: boolean
  blogProfileId?: boolean
  content?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type BlogPostCommentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "blogPostId" | "blogProfileId" | "content" | "metadata" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["blogPostComment"]>
export type BlogPostCommentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  blogPost?: boolean | Prisma.BlogPostDefaultArgs<ExtArgs>
  blogProfile?: boolean | Prisma.BlogProfileDefaultArgs<ExtArgs>
}
export type BlogPostCommentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  blogPost?: boolean | Prisma.BlogPostDefaultArgs<ExtArgs>
  blogProfile?: boolean | Prisma.BlogProfileDefaultArgs<ExtArgs>
}
export type BlogPostCommentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  blogPost?: boolean | Prisma.BlogPostDefaultArgs<ExtArgs>
  blogProfile?: boolean | Prisma.BlogProfileDefaultArgs<ExtArgs>
}

export type $BlogPostCommentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BlogPostComment"
  objects: {
    blogPost: Prisma.$BlogPostPayload<ExtArgs>
    blogProfile: Prisma.$BlogProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    blogPostId: string
    blogProfileId: string
    content: string
    metadata: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["blogPostComment"]>
  composites: {}
}

export type BlogPostCommentGetPayload<S extends boolean | null | undefined | BlogPostCommentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload, S>

export type BlogPostCommentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BlogPostCommentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BlogPostCommentCountAggregateInputType | true
  }

export interface BlogPostCommentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BlogPostComment'], meta: { name: 'BlogPostComment' } }
  /**
   * Find zero or one BlogPostComment that matches the filter.
   * @param {BlogPostCommentFindUniqueArgs} args - Arguments to find a BlogPostComment
   * @example
   * // Get one BlogPostComment
   * const blogPostComment = await prisma.blogPostComment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BlogPostCommentFindUniqueArgs>(args: Prisma.SelectSubset<T, BlogPostCommentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BlogPostComment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BlogPostCommentFindUniqueOrThrowArgs} args - Arguments to find a BlogPostComment
   * @example
   * // Get one BlogPostComment
   * const blogPostComment = await prisma.blogPostComment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BlogPostCommentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BlogPostCommentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BlogPostComment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogPostCommentFindFirstArgs} args - Arguments to find a BlogPostComment
   * @example
   * // Get one BlogPostComment
   * const blogPostComment = await prisma.blogPostComment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BlogPostCommentFindFirstArgs>(args?: Prisma.SelectSubset<T, BlogPostCommentFindFirstArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BlogPostComment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogPostCommentFindFirstOrThrowArgs} args - Arguments to find a BlogPostComment
   * @example
   * // Get one BlogPostComment
   * const blogPostComment = await prisma.blogPostComment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BlogPostCommentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BlogPostCommentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BlogPostComments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogPostCommentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BlogPostComments
   * const blogPostComments = await prisma.blogPostComment.findMany()
   * 
   * // Get first 10 BlogPostComments
   * const blogPostComments = await prisma.blogPostComment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const blogPostCommentWithIdOnly = await prisma.blogPostComment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BlogPostCommentFindManyArgs>(args?: Prisma.SelectSubset<T, BlogPostCommentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BlogPostComment.
   * @param {BlogPostCommentCreateArgs} args - Arguments to create a BlogPostComment.
   * @example
   * // Create one BlogPostComment
   * const BlogPostComment = await prisma.blogPostComment.create({
   *   data: {
   *     // ... data to create a BlogPostComment
   *   }
   * })
   * 
   */
  create<T extends BlogPostCommentCreateArgs>(args: Prisma.SelectSubset<T, BlogPostCommentCreateArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BlogPostComments.
   * @param {BlogPostCommentCreateManyArgs} args - Arguments to create many BlogPostComments.
   * @example
   * // Create many BlogPostComments
   * const blogPostComment = await prisma.blogPostComment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BlogPostCommentCreateManyArgs>(args?: Prisma.SelectSubset<T, BlogPostCommentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BlogPostComments and returns the data saved in the database.
   * @param {BlogPostCommentCreateManyAndReturnArgs} args - Arguments to create many BlogPostComments.
   * @example
   * // Create many BlogPostComments
   * const blogPostComment = await prisma.blogPostComment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BlogPostComments and only return the `id`
   * const blogPostCommentWithIdOnly = await prisma.blogPostComment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BlogPostCommentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BlogPostCommentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BlogPostComment.
   * @param {BlogPostCommentDeleteArgs} args - Arguments to delete one BlogPostComment.
   * @example
   * // Delete one BlogPostComment
   * const BlogPostComment = await prisma.blogPostComment.delete({
   *   where: {
   *     // ... filter to delete one BlogPostComment
   *   }
   * })
   * 
   */
  delete<T extends BlogPostCommentDeleteArgs>(args: Prisma.SelectSubset<T, BlogPostCommentDeleteArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BlogPostComment.
   * @param {BlogPostCommentUpdateArgs} args - Arguments to update one BlogPostComment.
   * @example
   * // Update one BlogPostComment
   * const blogPostComment = await prisma.blogPostComment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BlogPostCommentUpdateArgs>(args: Prisma.SelectSubset<T, BlogPostCommentUpdateArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BlogPostComments.
   * @param {BlogPostCommentDeleteManyArgs} args - Arguments to filter BlogPostComments to delete.
   * @example
   * // Delete a few BlogPostComments
   * const { count } = await prisma.blogPostComment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BlogPostCommentDeleteManyArgs>(args?: Prisma.SelectSubset<T, BlogPostCommentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BlogPostComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogPostCommentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BlogPostComments
   * const blogPostComment = await prisma.blogPostComment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BlogPostCommentUpdateManyArgs>(args: Prisma.SelectSubset<T, BlogPostCommentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BlogPostComments and returns the data updated in the database.
   * @param {BlogPostCommentUpdateManyAndReturnArgs} args - Arguments to update many BlogPostComments.
   * @example
   * // Update many BlogPostComments
   * const blogPostComment = await prisma.blogPostComment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BlogPostComments and only return the `id`
   * const blogPostCommentWithIdOnly = await prisma.blogPostComment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BlogPostCommentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BlogPostCommentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BlogPostComment.
   * @param {BlogPostCommentUpsertArgs} args - Arguments to update or create a BlogPostComment.
   * @example
   * // Update or create a BlogPostComment
   * const blogPostComment = await prisma.blogPostComment.upsert({
   *   create: {
   *     // ... data to create a BlogPostComment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BlogPostComment we want to update
   *   }
   * })
   */
  upsert<T extends BlogPostCommentUpsertArgs>(args: Prisma.SelectSubset<T, BlogPostCommentUpsertArgs<ExtArgs>>): Prisma.Prisma__BlogPostCommentClient<runtime.Types.Result.GetResult<Prisma.$BlogPostCommentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BlogPostComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogPostCommentCountArgs} args - Arguments to filter BlogPostComments to count.
   * @example
   * // Count the number of BlogPostComments
   * const count = await prisma.blogPostComment.count({
   *   where: {
   *     // ... the filter for the BlogPostComments we want to count
   *   }
   * })
  **/
  count<T extends BlogPostCommentCountArgs>(
    args?: Prisma.Subset<T, BlogPostCommentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BlogPostCommentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BlogPostComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogPostCommentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BlogPostCommentAggregateArgs>(args: Prisma.Subset<T, BlogPostCommentAggregateArgs>): Prisma.PrismaPromise<GetBlogPostCommentAggregateType<T>>

  /**
   * Group by BlogPostComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlogPostCommentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BlogPostCommentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BlogPostCommentGroupByArgs['orderBy'] }
      : { orderBy?: BlogPostCommentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BlogPostCommentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBlogPostCommentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BlogPostComment model
 */
readonly fields: BlogPostCommentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BlogPostComment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BlogPostCommentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  blogPost<T extends Prisma.BlogPostDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BlogPostDefaultArgs<ExtArgs>>): Prisma.Prisma__BlogPostClient<runtime.Types.Result.GetResult<Prisma.$BlogPostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  blogProfile<T extends Prisma.BlogProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BlogProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__BlogProfileClient<runtime.Types.Result.GetResult<Prisma.$BlogProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BlogPostComment model
 */
export interface BlogPostCommentFieldRefs {
  readonly id: Prisma.FieldRef<"BlogPostComment", 'String'>
  readonly blogPostId: Prisma.FieldRef<"BlogPostComment", 'String'>
  readonly blogProfileId: Prisma.FieldRef<"BlogPostComment", 'String'>
  readonly content: Prisma.FieldRef<"BlogPostComment", 'String'>
  readonly metadata: Prisma.FieldRef<"BlogPostComment", 'Json'>
  readonly createdAt: Prisma.FieldRef<"BlogPostComment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BlogPostComment", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"BlogPostComment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BlogPostComment findUnique
 */
export type BlogPostCommentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * Filter, which BlogPostComment to fetch.
   */
  where: Prisma.BlogPostCommentWhereUniqueInput
}

/**
 * BlogPostComment findUniqueOrThrow
 */
export type BlogPostCommentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * Filter, which BlogPostComment to fetch.
   */
  where: Prisma.BlogPostCommentWhereUniqueInput
}

/**
 * BlogPostComment findFirst
 */
export type BlogPostCommentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * Filter, which BlogPostComment to fetch.
   */
  where?: Prisma.BlogPostCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogPostComments to fetch.
   */
  orderBy?: Prisma.BlogPostCommentOrderByWithRelationInput | Prisma.BlogPostCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BlogPostComments.
   */
  cursor?: Prisma.BlogPostCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogPostComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogPostComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BlogPostComments.
   */
  distinct?: Prisma.BlogPostCommentScalarFieldEnum | Prisma.BlogPostCommentScalarFieldEnum[]
}

/**
 * BlogPostComment findFirstOrThrow
 */
export type BlogPostCommentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * Filter, which BlogPostComment to fetch.
   */
  where?: Prisma.BlogPostCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogPostComments to fetch.
   */
  orderBy?: Prisma.BlogPostCommentOrderByWithRelationInput | Prisma.BlogPostCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BlogPostComments.
   */
  cursor?: Prisma.BlogPostCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogPostComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogPostComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BlogPostComments.
   */
  distinct?: Prisma.BlogPostCommentScalarFieldEnum | Prisma.BlogPostCommentScalarFieldEnum[]
}

/**
 * BlogPostComment findMany
 */
export type BlogPostCommentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * Filter, which BlogPostComments to fetch.
   */
  where?: Prisma.BlogPostCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlogPostComments to fetch.
   */
  orderBy?: Prisma.BlogPostCommentOrderByWithRelationInput | Prisma.BlogPostCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BlogPostComments.
   */
  cursor?: Prisma.BlogPostCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlogPostComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlogPostComments.
   */
  skip?: number
  distinct?: Prisma.BlogPostCommentScalarFieldEnum | Prisma.BlogPostCommentScalarFieldEnum[]
}

/**
 * BlogPostComment create
 */
export type BlogPostCommentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * The data needed to create a BlogPostComment.
   */
  data: Prisma.XOR<Prisma.BlogPostCommentCreateInput, Prisma.BlogPostCommentUncheckedCreateInput>
}

/**
 * BlogPostComment createMany
 */
export type BlogPostCommentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BlogPostComments.
   */
  data: Prisma.BlogPostCommentCreateManyInput | Prisma.BlogPostCommentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BlogPostComment createManyAndReturn
 */
export type BlogPostCommentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * The data used to create many BlogPostComments.
   */
  data: Prisma.BlogPostCommentCreateManyInput | Prisma.BlogPostCommentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BlogPostComment update
 */
export type BlogPostCommentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * The data needed to update a BlogPostComment.
   */
  data: Prisma.XOR<Prisma.BlogPostCommentUpdateInput, Prisma.BlogPostCommentUncheckedUpdateInput>
  /**
   * Choose, which BlogPostComment to update.
   */
  where: Prisma.BlogPostCommentWhereUniqueInput
}

/**
 * BlogPostComment updateMany
 */
export type BlogPostCommentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BlogPostComments.
   */
  data: Prisma.XOR<Prisma.BlogPostCommentUpdateManyMutationInput, Prisma.BlogPostCommentUncheckedUpdateManyInput>
  /**
   * Filter which BlogPostComments to update
   */
  where?: Prisma.BlogPostCommentWhereInput
  /**
   * Limit how many BlogPostComments to update.
   */
  limit?: number
}

/**
 * BlogPostComment updateManyAndReturn
 */
export type BlogPostCommentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * The data used to update BlogPostComments.
   */
  data: Prisma.XOR<Prisma.BlogPostCommentUpdateManyMutationInput, Prisma.BlogPostCommentUncheckedUpdateManyInput>
  /**
   * Filter which BlogPostComments to update
   */
  where?: Prisma.BlogPostCommentWhereInput
  /**
   * Limit how many BlogPostComments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BlogPostComment upsert
 */
export type BlogPostCommentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * The filter to search for the BlogPostComment to update in case it exists.
   */
  where: Prisma.BlogPostCommentWhereUniqueInput
  /**
   * In case the BlogPostComment found by the `where` argument doesn't exist, create a new BlogPostComment with this data.
   */
  create: Prisma.XOR<Prisma.BlogPostCommentCreateInput, Prisma.BlogPostCommentUncheckedCreateInput>
  /**
   * In case the BlogPostComment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BlogPostCommentUpdateInput, Prisma.BlogPostCommentUncheckedUpdateInput>
}

/**
 * BlogPostComment delete
 */
export type BlogPostCommentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
  /**
   * Filter which BlogPostComment to delete.
   */
  where: Prisma.BlogPostCommentWhereUniqueInput
}

/**
 * BlogPostComment deleteMany
 */
export type BlogPostCommentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BlogPostComments to delete
   */
  where?: Prisma.BlogPostCommentWhereInput
  /**
   * Limit how many BlogPostComments to delete.
   */
  limit?: number
}

/**
 * BlogPostComment without action
 */
export type BlogPostCommentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlogPostComment
   */
  select?: Prisma.BlogPostCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlogPostComment
   */
  omit?: Prisma.BlogPostCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogPostCommentInclude<ExtArgs> | null
}
